version: "3"
services:
    mssql-account:
        image: microsoft/mssql-server-linux:latest
        container_name: mssql-account
        restart: "always"
        ports:
          - "1433:1433"
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=sa@12345

    mongodb-account:
      image: "mongo:latest"
      container_name: mongodb-account
      ports:
        - "27017:27017"
      restart: always
      volumes:
        - ./.docker/data/db:/data/db

    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      volumes:
          - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
          - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
          - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
      environment:
          RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
          RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
          RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      ports:
          - 5672:5672
          - 15672:15672