version: "3"
services:
    mssql:
        image: microsoft/mssql-server-linux:latest
        container_name: db
        restart: "always"
        ports:
          - "1433:1433"
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=sa@12345

    mongodb:
      image: "mongo:latest"
      container_name: mongodb
      ports:
        - "27017:27017"
      restart: always
      volumes:
        - ./data/db:/data/db

    zookeeper:
      container_name: zookeeper
      image: wurstmeister/zookeeper:latest
      ports:
        - "2181:2181"
    kafka:
      container_name: kafka
      image: wurstmeister/kafka:2.11-1.1.0
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #   KAFKA_CREATE_TOPICS: "topic:1:1"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock